version: '2'

x-jupyter-build-opts: &x-jupyter-build-opts
  build:
    context: ./jupyter

x-logging-opts: &x-logging-opts
  logging:
    driver: 'json-file'
    options:
      max-size: '20M'
      max-file: '5'

services:

  crt-learning:
    <<: *x-jupyter-build-opts
    <<: *x-logging-opts
    image: jupyter/minimal-notebook
    container_name: ${NAME}-jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - '8888:8888/tcp'
    volumes:
      - ./notebook:/home/jovyan
