version: '2.1'

x-crt-learning-build-opts: &x-crt-learning-build-opts
  build:
    context: ./crt-learning

x-logging-opts: &x-logging-opts
  logging:
    driver: 'json-file'
    options:
      max-size: '20M'
      max-file: '5'

services:

  clickhouse:
    <<: *x-logging-opts
    image: yandex/clickhouse-server
    container_name: ${NAME}-clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - '8123:8123/tcp'
      - '9000:9000/tcp'
    volumes:
      - ./ch-conf:/etc/clickhouse-server
      - ./ch-data:/var/lib/clickhouse
      - ./ch-log:/var/log/clickhouse-server
    healthcheck:
      test: "clickhouse-client --port=9000 --query='SELECT 1'"
      interval: 5s
      timeout: 30s
      retries: 10

  crt-learning:
    <<: *x-crt-learning-build-opts
    <<: *x-logging-opts
    container_name: ${NAME}
