version: '2'

x-jupyter-build-opts: &x-jupyter-build-opts
  build:
    context: ./jupyter

x-logging-opts: &x-logging-opts
  logging:
    driver: 'json-file'
    options:
      max-size: '20M'
      max-file: '5'

services:

  crt-learning:
    <<: *x-jupyter-build-opts
    <<: *x-logging-opts
    image: jupyter/minimal-notebook
    container_name: ${NAME}-jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - '8888:8888/tcp'
    volumes:
      - ./notebook:/home/jovyan/work
      - ./jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py

    # http://localhost:8888/?token=6e8e8040fc2661efc315f283f678ade211617407ced6c1ef :: /home/jovyan
    

  # redis:
  #   <<: *x-logging-opts
  #   image: redis
  #   container_name: ${NAME}-redis
  #   volumes:
  #     - './data-redis:/data:rw'

  # postgres:
  #   <<: *x-logging-opts
  #   image: postgres
  #   container_name: ${NAME}-postgres
  #   environment:
  #     POSTGRES_DB: superset
  #     POSTGRES_PASSWORD: superset
  #     POSTGRES_USER: superset
  #   volumes:
  #     - './data-postgres:/var/lib/postgresql/data:rw'

  # superset:
  #   <<: *x-logging-opts
  #   image: amancevice/superset
  #   container_name: ${NAME}-superset
  #   depends_on:
  #     - postgres
  #     - redis
  #   # environment:
  #   #   MAPBOX_API_KEY: ${MAPBOX_API_KEY}
  #   ports:
  #     - '8088:8088/tcp'
  #   volumes:
  #     - './superset:/etc/superset:rw'
